# Generated by Django 4.2 on 2023-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
