# Generated by Django 4.2 on 2023-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(error_messages={'unique': 'A user with that Mobile Number already exists.'}, max_length=11, unique=True),
        ),
    ]
