# Generated by Django 4.2 on 2023-04-23 21:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_wallet_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
