# Generated by Django 4.2.3 on 2023-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_wallet_nuban'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='nuban',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
