# Generated by Django 4.2.3 on 2023-07-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wallet_nuban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='account_preference',
            new_name='account_reference',
        ),
    ]
