# Generated by Django 4.2.3 on 2023-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_account_preference_wallet_account_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
